### ISSUE TITLE
Manage profile.d directory optionally

### ISSUE THREAD

**Issue by hdep** [jessereynolds/puppet-proxy_client#1]
Hi @jessereynolds 

This is a great module. I have a small issue though, by default the module ensure /etc/profile.d is a directory, this cause me duplicate resource definition if I want to use another module for managing bashrc.

I could add a new variable in order to be able to manage or not this directory. 
Are you interested for a PR ? 

Regards,

**Comment by jessereynolds** [comment]
Good point @hdep yes that’d be a good PR. Although this module is pretty trivial :-)

**Comment by hdep** [comment]
yes it is trivial, but I use r10k and get this module from the forge, so I prefer not  forking it into my gitlab :) 
I'll work on this PR then !

**Comment by hdep** [comment]
fixed in #2 thanks @jessereynolds ! 
just need a new release if you can :)

**Comment by jessereynolds** [comment]
Yep, release coming right up

**Comment by jessereynolds** [comment]
@hdep v0.2.0 is on the forge now with your updates
